import { execSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(__dirname, '../src/environments/version.ts');

function git(args) {
  try {
    return execSync(`git ${args}`, { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch {
    return '';
  }
}

function isDirty() {
  try {
    execSync('git diff --quiet HEAD', { stdio: 'ignore' });
    return false;
  } catch {
    return true;
  }
}

const commit = git('rev-parse --short HEAD') || 'unknown';
const dirty = commit !== 'unknown' && isDirty() ? '-dirty' : '';

const now = new Date();
const yyyy = now.getFullYear();
const mm = String(now.getMonth() + 1).padStart(2, '0');
const dd = String(now.getDate()).padStart(2, '0');
const calver = `${yyyy}.${mm}.${dd}`;
const buildDate = now.toISOString();

const contents = `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit.
export const APP_VERSION = {
  version: '${calver}',
  commit: '${commit}${dirty}',
  buildDate: '${buildDate}',
} as const;
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, contents);
console.log(`[version] ${calver} · ${commit}${dirty}`);
